# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 11:22
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=10)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=b'userProfiles/')),
                ('date_of_birth', models.DateTimeField()),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2016, 10, 15, 14, 52, 25, 420802))),
                ('country', django_countries.fields.CountryField(default=b'Iran', max_length=2)),
                ('national_code', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='commonuser',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ID', to='interpay.UserProfile'),
        ),
    ]
