# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-28 11:31
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('method', models.PositiveSmallIntegerField(choices=[(1, b'Debit'), (2, b'Withdraw')], default=1)),
                ('name', models.CharField(max_length=254)),
                ('when_opened', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('cur_code', models.CharField(default=b'RLS', max_length=3, verbose_name='cur_code')),
                ('account_id', models.CharField(max_length=24, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z]*$', b'Only alphanumeric characters are allowed.')])),
            ],
        ),
        migrations.CreateModel(
            name='CommonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('cur_code', models.CharField(default=b'USD', max_length=3, verbose_name='cur_code')),
                ('be', models.IntegerField(default=b'123')),
                ('status', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_set', to='interpay.BankAccount')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('comment', models.CharField(max_length=255)),
                ('cur_code', models.CharField(default=b'USD', max_length=3, verbose_name='cur_code')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_transfers', to='interpay.BankAccount')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_transfers', to='interpay.BankAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cur_code', models.CharField(default=b'USD', max_length=3, verbose_name='cur_code')),
                ('deposit_charge_percent', models.FloatField(default=2)),
                ('credit_percent', models.FloatField(default=98)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=10)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=b'userProfiles/')),
                ('date_of_birth', models.DateTimeField()),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2016, 12, 28, 15, 0, 54, 697000))),
                ('country', django_countries.fields.CountryField(default=b'Iran', max_length=2)),
                ('national_code', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('national_card_photo', models.ImageField(blank=True, null=True, upload_to=b'nationalCardScans/')),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verif_code_user', to='interpay.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('cur_code', models.CharField(default=b'USD', max_length=3, verbose_name='cur_code')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_set', to='interpay.BankAccount')),
                ('banker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interpay.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='deposit',
            name='banker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interpay.UserProfile'),
        ),
        migrations.AddField(
            model_name='commonuser',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ID', to='interpay.UserProfile'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='w_accounts', to='interpay.UserProfile'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='spectators',
            field=models.ManyToManyField(related_name='r_accounts', to='interpay.UserProfile'),
        ),
    ]
