# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 10:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interpay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='banker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interpay.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 2, 14, 18, 24, 152000)),
        ),
    ]
