# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 14:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpay', '0002_auto_20161015_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 18, 18, 17, 42, 752479)),
        ),
    ]
