# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 15:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpay', '0003_auto_20161018_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 19, 18, 57, 23, 63067)),
        ),
    ]
