# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 11:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpay', '0007_auto_20161110_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='credit_percent',
            field=models.FloatField(default=98),
        ),
        migrations.AlterField(
            model_name='rule',
            name='deposit_charge_percent',
            field=models.FloatField(default=99),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 10, 15, 2, 9, 341653)),
        ),
    ]
