# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 12:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpay', '0010_auto_20161110_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 10, 16, 0, 1, 721925)),
        ),
    ]
