# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 12:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpay', '0012_auto_20161110_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
