# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import interpay.models


class Migration(migrations.Migration):

    dependencies = [
        ('interpay', '0014_auto_20161110_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='id',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_id',
            field=models.BigIntegerField(default=interpay.models.make_id, primary_key=True, serialize=False),
        ),
    ]
