# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpay', '0016_auto_20161110_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='cur_code',
            field=models.CharField(default=b'USD', max_length=3, verbose_name='cur_code'),
        ),
    ]
