# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 10:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpay', '0021_auto_20161212_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 12, 13, 36, 25, 773654)),
        ),
    ]
