# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-25 13:54
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpay', '0022_auto_20161212_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='total',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='deposit',
            old_name='when',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='total',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='when',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='withdraw',
            old_name='total',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='withdraw',
            old_name='when',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_id',
            field=models.CharField(max_length=24, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z]*$', b'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='cur_code',
            field=models.CharField(default=b'RLS', max_length=3, verbose_name='cur_code'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 25, 17, 23, 30, 777855)),
        ),
    ]
